_BASE_: clip_vitb_384_isaid_attr64_dual_teacher_aff_residual_moe.yaml

MODEL:
  SEM_SEG_HEAD:
    ATTR_FUSION:
      DATABASE_PATH: "attributes_text/rskt_seg/iSAID_train_desc_remoteclip_b32_cluster_20_embedding_bank.pth"
      NUM_CLUSTERS: 20

OUTPUT_DIR: "output/clip_vitb_384_isaid_attr20_dual_teacher_aff_residual_moe_remoteclip_attr_content1_context0p1_2gpu_bs4"
