_BASE_: eva_vitb_384.yaml

MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 15
    TRAIN_CLASS_JSON: "datasets/iSAID.json"
    TEST_CLASS_JSON: "datasets/iSAID.json"
    CACHE_DIR: "pretrained/declip_eva_b16_dinov2b_coco_full_retry1_epoch_latest_state_dict.pt"
    ATTR_FUSION:
      ENABLED: true
      DATABASE_PATH: "attributes_text/rskt_seg/iSAID_train_desc_declip_eva_b16_cluster_64_embedding_bank.pth"
      NUM_CLUSTERS: 64
      TOP_K: 0.9

DATASETS:
  TRAIN: ("iSAID_train_sem_seg",)
  TEST: ("iSAID_val_sem_seg",)

SOLVER:
  IMS_PER_BATCH: 8
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0002
  MAX_ITER: 60000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 0.01
  CHECKPOINT_PERIOD: 5000

TEST:
  EVAL_PERIOD: 5000
  SLIDING_WINDOW: false

OUTPUT_DIR: "output/eva_vitb_384_isaid_attr64_declip_rskt_protocol_4gpu_bs2"
