_BASE_: eva_vitb_384_isaid_attr64_rs_dino_rskt_protocol.yaml

MODEL:
  SEM_SEG_HEAD:
    FEATURE_FUSION:
      TYPE: "aff_residual_moe"

OUTPUT_DIR: "output/eva_vitb_384_isaid_attr64_rs_dino_aff_residual_moe_2gpu_bs4"
