#!/usr/bin/env python3
"""Generate ExCEL-style attribute descriptions for RSKT-Seg train classes."""

from __future__ import annotations

import json
from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "attributes_text" / "rskt_seg_train_descriptors.json"


ATTRIBUTES = {
    "airplane": [
        "it has a long narrow fuselage with two lateral wings.",
        "its footprint is usually bilaterally symmetric around the fuselage.",
        "the wings form a strong cross-like silhouette from overhead.",
        "it often appears bright against darker runways or ground.",
        "a tail assembly is visible at the rear of the body.",
        "the nose is tapered while the main body is elongated.",
        "large examples may cast narrow wing and fuselage shadows.",
        "it is commonly located on runways, taxiways, or airport aprons.",
        "parked examples often align in rows beside terminal buildings.",
        "its smooth surface has little internal texture at satellite scale.",
        "the wings are wider than the tail stabilizers.",
        "jet engines may appear as small pods beneath the wings.",
        "its orientation can vary freely within an airport scene.",
        "it is larger and more elongated than nearby road vehicles.",
        "the object boundary is usually sharp on paved airport surfaces.",
        "commercial types often have swept wings and a cylindrical body.",
        "small types may show straight wings and a compact fuselage.",
        "it may occur alone on a runway or clustered on an apron.",
        "its tail points opposite the tapered nose along the main axis.",
        "overhead imagery emphasizes shape more than color or markings.",
    ],
    "bare soil": [
        "it forms exposed earth patches without dense vegetation cover.",
        "its color ranges from pale tan to reddish or dark brown.",
        "the surface often has a granular or mottled texture.",
        "its boundary may be irregular where soil meets vegetation.",
        "it commonly occurs in construction sites, fields, and cleared land.",
        "dry areas usually appear brighter than moist exposed soil.",
        "vehicle tracks or grading lines may cross the surface.",
        "it lacks the regular roof patterns associated with built areas.",
        "large patches can have smooth interiors with uneven edges.",
        "small patches often fill gaps between plants or structures.",
        "it may be surrounded by grass, crops, pavement, or woodland.",
        "freshly disturbed soil can show linear excavation patterns.",
        "its tone changes with geology, moisture, and illumination.",
        "the region usually casts no coherent object shadow.",
        "plowed soil may show repeated parallel furrows.",
        "compacted soil can resemble pavement but has softer boundaries.",
        "erosion may create branching channels across sloped patches.",
        "the texture is less uniform than concrete or asphalt.",
        "seasonal vegetation loss can expose temporary soil areas.",
        "overhead views show it as a continuous land-cover surface.",
    ],
    "buildings": [
        "they have compact roof footprints with straight or polygonal edges.",
        "roof colors may be white, gray, red, blue, or brown.",
        "their boundaries are usually sharper than surrounding vegetation.",
        "they often cast directional shadows beside the roof footprint.",
        "rectangular buildings commonly align with streets or parcels.",
        "dense groups form repeated roof patterns in urban blocks.",
        "large buildings may have broad flat roofs with rooftop equipment.",
        "small buildings often appear as isolated rectangles near roads.",
        "pitched roofs may show two tonal planes divided by a ridge.",
        "flat roofs usually have relatively uniform interior texture.",
        "they are commonly connected to roads, driveways, or courtyards.",
        "industrial roofs are often larger and brighter than residential roofs.",
        "residential buildings frequently occur among trees and small yards.",
        "their geometric outlines distinguish them from natural land cover.",
        "adjacent structures may merge into complex roof clusters.",
        "tall buildings create longer shadows than low nearby structures.",
        "roof orientation can vary with the local street network.",
        "some roofs contain skylights, vents, or contrasting panels.",
        "building density ranges from isolated rural sites to compact cities.",
        "overhead imagery primarily reveals roofs rather than vertical facades.",
    ],
    "cars": [
        "they appear as very small elongated rectangles on roads or parking areas.",
        "their colors may be white, dark, gray, red, or blue.",
        "individual cars often have a bright roof and darker windows.",
        "they are much smaller than buildings and large transport vehicles.",
        "parked cars commonly form evenly spaced rows.",
        "moving cars align with the direction of road lanes.",
        "their short narrow shadows may indicate vehicle height.",
        "they often cluster near buildings, terminals, or commercial areas.",
        "a car footprint is usually longer than it is wide.",
        "dense parking lots create repeated dot-like or dash-like patterns.",
        "isolated cars can be difficult to separate from roof equipment.",
        "their boundaries are clearest on uniform asphalt backgrounds.",
        "road markings may appear longer and thinner than nearby cars.",
        "cars on bright pavement may appear dark through contrast.",
        "cars on dark pavement may appear as bright compact objects.",
        "their orientation varies in parking lots but follows lanes on roads.",
        "adjacent cars may merge when image resolution is limited.",
        "the roof-centered overhead view hides wheels and side details.",
        "vehicle queues form short repeated segments along road corridors.",
        "they may occur beside curbs, driveways, and intersection approaches.",
    ],
    "chaparral": [
        "it forms dense low shrub cover with irregular natural boundaries.",
        "the canopy has a coarse mottled texture in overhead imagery.",
        "its color varies from olive green to dry gray-brown.",
        "individual shrubs may create repeated small rounded crowns.",
        "it commonly covers dry hillsides and undeveloped terrain.",
        "patches are less geometrically organized than agricultural fields.",
        "the surface usually appears lower and rougher than mature forest.",
        "exposed soil may be visible between sparse shrub crowns.",
        "dense areas form nearly continuous vegetation with speckled tones.",
        "its edges often follow terrain, drainage, or disturbance patterns.",
        "seasonal dryness can shift green patches toward brown tones.",
        "narrow trails or firebreaks may divide large chaparral regions.",
        "it rarely shows the regular row structure of planted crops.",
        "shrub shadows are short and diffuse compared with tree shadows.",
        "it may border grassland, bare soil, roads, or woodland.",
        "burned or cleared gaps create abrupt dark or pale openings.",
        "the vegetation height appears relatively uniform across broad patches.",
        "rugged terrain can create illumination variation within the cover.",
        "its texture is more clumped than grass and finer than tree canopy.",
        "overhead views show a natural mosaic of shrubs and exposed ground.",
    ],
    "court": [
        "it is a flat geometric playing surface with a clear outer boundary.",
        "the footprint is usually rectangular or nearly rectangular.",
        "painted lines divide the surface into regular playing zones.",
        "its interior texture is smoother than surrounding vegetation.",
        "surface colors may be green, blue, red, tan, or gray.",
        "it commonly occurs near schools, parks, and recreation complexes.",
        "fences may create thin outlines or narrow shadows around the court.",
        "multiple courts often appear in parallel repeated arrangements.",
        "the long and short sides meet at sharp right-angled corners.",
        "players and equipment are usually tiny relative to the surface.",
        "the court contrasts strongly with grass or bare soil nearby.",
        "access paths often connect it to buildings or parking areas.",
        "line markings are brighter than the main playing surface.",
        "the surface generally casts no broad structural shadow.",
        "surrounding light poles may cast thin elongated shadows.",
        "weathering can make painted boundaries faint or discontinuous.",
        "its regular geometry distinguishes it from natural open ground.",
        "adjacent courts may share fences or paved margins.",
        "spectator areas may appear as narrow structures along one side.",
        "overhead imagery emphasizes boundary shape and internal line layout.",
    ],
    "dock": [
        "it projects from a shoreline into adjacent water.",
        "its footprint is usually long and narrow with straight edges.",
        "wooden docks often appear tan or gray against dark water.",
        "concrete docks may appear bright and broad in overhead views.",
        "boats are frequently moored along one or both sides.",
        "finger piers can create repeated comb-like patterns.",
        "the structure connects water access to land or harbor facilities.",
        "its boundary is sharp where the platform meets open water.",
        "narrow dock shadows may fall directly onto the water surface.",
        "it often occurs in marinas, ports, lakes, or sheltered bays.",
        "the main axis is commonly perpendicular or oblique to the shoreline.",
        "floating sections may show slight offsets or segmented joints.",
        "large cargo docks adjoin paved yards, cranes, or warehouses.",
        "small recreational docks connect to houses or shoreline paths.",
        "water may be visible between parallel dock branches.",
        "mooring posts appear as tiny points beside the platform.",
        "its surface texture is smoother and more geometric than the shore.",
        "wake patterns or boats may occur near the outer end.",
        "the dock remains narrower than most neighboring land structures.",
        "overhead imagery reveals a clear land-to-water structural transition.",
    ],
    "field": [
        "it forms a broad open parcel with recognizable boundaries.",
        "the footprint may be rectangular, polygonal, or terrain-following.",
        "crop rows can create fine parallel or curved line textures.",
        "its color varies with crop type, season, soil, and moisture.",
        "neighboring fields often form a patchwork of contrasting tones.",
        "the interior is usually more uniform than woodland or urban areas.",
        "roads, hedges, or drainage channels may define its edges.",
        "harvested fields often appear tan with visible stubble patterns.",
        "growing fields commonly appear green with regular planted texture.",
        "plowed fields may show dark or brown repeated furrows.",
        "irrigation can produce circular or strongly patterned crop regions.",
        "farm buildings may occur near the edge of a field complex.",
        "tree lines sometimes separate adjacent agricultural parcels.",
        "large fields cast no coherent object shadow across the surface.",
        "patch boundaries are straighter than those of natural grassland.",
        "bare gaps or tractor tracks may interrupt an otherwise uniform cover.",
        "seasonal changes can substantially alter its tone and texture.",
        "the area is generally larger than individual recreational courts.",
        "sloped fields may show contour-aligned planting lines.",
        "overhead imagery emphasizes parcel geometry and repeated cultivation patterns.",
    ],
    "grass": [
        "it forms low continuous vegetation with a fine even texture.",
        "healthy grass commonly appears bright to medium green.",
        "dry grass may appear pale yellow, tan, or brown.",
        "its surface is smoother than shrubs or tree canopy.",
        "patch boundaries may follow lawns, fields, roads, or natural terrain.",
        "mowed areas often show subtle stripes or uniform short cover.",
        "it commonly surrounds buildings, courts, roads, and trees.",
        "individual tree crowns may interrupt otherwise continuous grass.",
        "the cover usually produces little or no visible shadow.",
        "bare soil patches may appear within worn or sparse grass.",
        "urban lawns often have geometric boundaries and regular maintenance.",
        "natural grassland tends to have irregular edges and tonal variation.",
        "sports turf may appear as a bright rectangular green area.",
        "moist grass can be darker than neighboring dry vegetation.",
        "paths and tracks create narrow pale lines across the cover.",
        "its fine texture distinguishes it from coarse chaparral.",
        "its low height distinguishes it from trees through minimal shadows.",
        "seasonal mowing can create adjacent bands of different tone.",
        "small grass strips often occur along medians and property edges.",
        "overhead views show it primarily as a continuous green land cover.",
    ],
    "mobile home": [
        "it has a long narrow rectangular roof footprint.",
        "the roof is often bright white, gray, or light metal.",
        "units commonly appear in parallel rows with regular spacing.",
        "the structure is smaller and narrower than most permanent buildings.",
        "short driveways or parked cars often occur beside each unit.",
        "it may have a small porch, awning, or attached extension.",
        "the roof interior is usually smooth with few visible details.",
        "its straight edges and sharp corners form a simple geometry.",
        "mobile-home parks create repeated elongated roof patterns.",
        "small yards or narrow roads separate neighboring units.",
        "the long axis often aligns with the local access road.",
        "a short shadow may fall along one side of the structure.",
        "individual units can occur on rural lots or construction sites.",
        "the footprint resembles a trailer but remains fixed within a parcel.",
        "roof vents may appear as tiny dark or bright points.",
        "vegetation may partially obscure units in older residential parks.",
        "paired units may form a wider combined rectangular footprint.",
        "its regular repetition distinguishes it from industrial storage objects.",
        "utility paths and compact parking spaces often surround the unit.",
        "overhead imagery emphasizes the elongated roof and organized settlement pattern.",
    ],
    "pavement": [
        "it forms a flat hardened surface with a smooth visual texture.",
        "its tone ranges from dark asphalt to pale concrete.",
        "the boundary is often geometric where pavement meets vegetation.",
        "road markings may create bright linear patterns on the surface.",
        "it commonly covers roads, parking lots, plazas, and airport aprons.",
        "cracks, patches, and repairs can create subtle tonal variation.",
        "the surface itself casts no coherent object shadow.",
        "vehicles and buildings often occur directly on or beside it.",
        "curbs may appear as thin bright lines along its edges.",
        "large paved regions usually have low internal texture.",
        "parking spaces produce repeated painted rectangular markings.",
        "intersections create connected angular or crossing pavement shapes.",
        "wet pavement may appear darker and slightly reflective.",
        "concrete sections can show repeated seams or slab boundaries.",
        "asphalt is generally more uniform than bare soil.",
        "paved paths are narrower and more regular than natural trails.",
        "tree or building shadows may extend across the surface.",
        "surface color can vary with age, material, and illumination.",
        "its continuous connectivity often follows transportation networks.",
        "overhead imagery reveals shape, markings, and adjacency more than height.",
    ],
    "sand": [
        "it appears as a pale granular surface with little vegetation.",
        "its color ranges from white and beige to golden or gray.",
        "the boundary may follow shorelines, dunes, or exposed deposits.",
        "wind can create ripples, ridges, or curved dune patterns.",
        "wet sand usually appears darker near the water edge.",
        "dry sand is often brighter than adjacent soil or rock.",
        "it commonly occurs on beaches, deserts, and river margins.",
        "the surface has soft natural edges rather than sharp geometry.",
        "footpaths or vehicle tracks may form narrow darker lines.",
        "sparse plants can appear as scattered dark points.",
        "dunes may cast smooth elongated shadows on one side.",
        "flat beach sand generally casts no coherent shadow.",
        "wave action can create parallel bands along a shoreline.",
        "its texture is finer and more uniform than rocky ground.",
        "sandbars appear as elongated pale forms within shallow water.",
        "deposits may transition gradually into bare soil or grass.",
        "bright roofs or concrete can resemble sand but have sharper edges.",
        "seasonal water levels can change the visible extent of sand.",
        "large areas may show broad tonal gradients caused by moisture.",
        "overhead views emphasize pale tone, soft texture, and landform patterns.",
    ],
    "sea": [
        "it forms an extensive continuous water region beside land or islands.",
        "deep areas commonly appear dark blue, navy, or blue-green.",
        "shallow coastal water may appear lighter or more turquoise.",
        "the surface texture is usually smooth at satellite scale.",
        "waves can create fine bright streaks or foam near shore.",
        "its boundary follows an irregular coastline or harbor edge.",
        "ships may appear as small elongated objects on the surface.",
        "cloud shadows can create broad dark patches over the water.",
        "sun glint may produce very bright reflective regions.",
        "sediment plumes can discolor water near river mouths.",
        "the region is generally larger and more open than inland water bodies.",
        "breakwaters and docks may project into coastal portions.",
        "wake lines may trail behind moving vessels.",
        "offshore water lacks the parcel structure of terrestrial land cover.",
        "coastal shallows may reveal submerged sand or reef patterns.",
        "the surface casts no stable object shadow of its own.",
        "color varies with depth, turbidity, weather, and illumination.",
        "shoreline foam can form a narrow bright boundary.",
        "islands appear as enclosed land regions within the sea.",
        "overhead imagery shows a broad low-texture area with natural boundaries.",
    ],
    "ship": [
        "it has an elongated hull with a pointed bow and broader stern.",
        "the object appears on water rather than on a road or runway.",
        "large ships often have a bright deck over a dark hull outline.",
        "its long axis may align with a channel, dock, or open-water route.",
        "a moving ship can leave a V-shaped or linear wake.",
        "stationary ships often lie parallel to docks or harbor quays.",
        "the hull forms a narrow compact silhouette against smooth water.",
        "cargo ships may show repeated rectangular containers on deck.",
        "tankers often have long uncluttered decks with central structures.",
        "small ships can appear as bright dashes in dark water.",
        "superstructures create compact bright regions near the center or stern.",
        "the vessel may cast a narrow shadow directly onto the water.",
        "multiple ships often cluster near ports or anchorage areas.",
        "its footprint is larger and more structured than a small boat wake.",
        "the bow direction can often be inferred from hull tapering.",
        "moored ships may be connected to land by thin gangways or lines.",
        "deck cranes can create small protrusions or narrow shadows.",
        "orientation varies freely in open water but is organized at berths.",
        "the sharp object boundary contrasts with the low-texture water surface.",
        "overhead imagery emphasizes hull shape, deck layout, and wake context.",
    ],
    "tanks": [
        "they appear as circular or cylindrical storage structures from overhead.",
        "their roofs are often bright white, gray, or metallic.",
        "multiple tanks commonly form regular clusters in industrial sites.",
        "a circular boundary distinguishes them from rectangular buildings.",
        "large tanks may show a central roof point or radial pattern.",
        "their smooth roofs have little internal texture.",
        "cylindrical walls can cast curved shadows beside the footprint.",
        "they often occur near pipelines, refineries, ports, or processing plants.",
        "containment berms may form rings or polygons around each tank.",
        "adjacent service roads create organized access patterns.",
        "tank diameters may vary within the same facility.",
        "dark tanks may blend with industrial surfaces but retain circular edges.",
        "floating-roof tanks can show concentric tonal rings.",
        "small tanks may resemble dots but appear in purposeful arrangements.",
        "their spacing is generally more regular than natural round features.",
        "pipes may appear as thin lines connecting neighboring tanks.",
        "the structures are larger than most vehicles and smaller than broad warehouses.",
        "shadows indicate vertical height despite the circular overhead footprint.",
        "groups often occupy paved or bare industrial compounds.",
        "overhead imagery emphasizes repeated circles and industrial context.",
    ],
    "trees": [
        "they form rounded or irregular crowns with coarse leafy texture.",
        "canopy color ranges from bright green to dark green or seasonal brown.",
        "individual crowns often cast distinct directional shadows.",
        "dense trees merge into continuous rough-textured canopy.",
        "isolated trees appear as compact crowns surrounded by grass or soil.",
        "their boundaries are softer and less geometric than building roofs.",
        "tree rows may align along roads, fields, rivers, or property edges.",
        "mature trees generally cast longer shadows than shrubs.",
        "different species create varied crown sizes, colors, and textures.",
        "leafless trees can show branching structure and sparse gray crowns.",
        "urban trees often occur between buildings, sidewalks, and parking areas.",
        "forest trees create a mottled pattern of highlights and shadows.",
        "canopies may partially obscure roads, roofs, and ground surfaces.",
        "orchard trees form highly regular grids of separated crowns.",
        "natural woodland has irregular spacing and mixed crown shapes.",
        "seasonal foliage changes can alter both tone and canopy density.",
        "wind or terrain may cause uneven illumination across the canopy.",
        "small gaps reveal understory, soil, or grass between crowns.",
        "their vertical structure is inferred from crown shadows and texture.",
        "overhead imagery emphasizes crown shape rather than trunks or branches.",
    ],
    "water": [
        "it forms a smooth low-texture surface with natural or engineered boundaries.",
        "its tone ranges from dark blue and green to brown or nearly black.",
        "rivers appear as elongated connected corridors through the landscape.",
        "lakes and ponds form enclosed regions with irregular or geometric edges.",
        "turbid water may appear lighter or browner than clear water.",
        "sun glint can create bright reflective patches on the surface.",
        "vegetation, banks, docks, or levees often define its boundary.",
        "boats may create small objects and wake lines on the surface.",
        "shadows from bridges or trees can darken localized areas.",
        "shallow water may reveal bottom texture or aquatic vegetation.",
        "reservoirs can have straight dam edges and branching shorelines.",
        "canals have narrow regular widths and engineered linear paths.",
        "floodwater spreads irregularly across normally terrestrial surfaces.",
        "the surface lacks the repeated parcel patterns of fields.",
        "wave texture is generally finer than vegetation texture.",
        "seasonal levels may expose pale banks around the water body.",
        "dark roofs can resemble water but have sharper geometric outlines.",
        "adjacent wetlands may create mixed water and vegetation patterns.",
        "its extent often follows topography and drainage networks.",
        "overhead imagery emphasizes tone, smoothness, and boundary continuity.",
    ],
    "storage tank": [
        "it has a circular roof footprint with a clearly defined rim.",
        "the roof is often white, silver, gray, or occasionally dark.",
        "multiple storage tanks commonly cluster in industrial compounds.",
        "its circular geometry is highly regular from overhead.",
        "large examples may show a central point or concentric roof rings.",
        "the smooth roof contrasts with textured surrounding ground.",
        "a curved shadow may reveal the cylindrical wall height.",
        "it often occurs near refineries, terminals, ports, or pipelines.",
        "containment walls can form larger circles or polygons around it.",
        "service roads frequently loop around or connect the structure.",
        "floating roofs may have distinct inner and outer tonal zones.",
        "pipes appear as thin lines leading from the tank area.",
        "the footprint is usually larger than a vehicle and smaller than a warehouse.",
        "neighboring tanks may have different diameters but similar appearance.",
        "its boundary remains circular despite varying viewing orientation.",
        "roof weathering can create patches without changing the overall shape.",
        "isolated tanks may stand beside factories or utility installations.",
        "regular spacing separates tank farms from natural circular features.",
        "small rooftop tanks are excluded by the larger ground-based context.",
        "overhead imagery emphasizes the circle, rim, shadow, and industrial setting.",
    ],
    "baseball diamond": [
        "it contains a fan-shaped outfield connected to an angular infield.",
        "the infield often appears as a tan dirt diamond within green grass.",
        "four bases define a small square rotated relative to the outfield.",
        "the home-plate corner points toward the curved outfield boundary.",
        "two foul lines extend outward in a broad V shape.",
        "the pitcher's mound may appear as a small central dirt circle.",
        "it commonly occurs in parks, schools, and sports complexes.",
        "dugouts may appear as narrow structures beside the infield.",
        "spectator stands can border the area behind home plate.",
        "multiple diamonds may share overlapping or adjacent outfields.",
        "the field has stronger radial geometry than rectangular courts.",
        "grass mowing can create subtle striped patterns in the outfield.",
        "fences may outline the curved outer edge of the playing area.",
        "light poles can cast thin elongated shadows around the field.",
        "the infield dirt contrasts clearly with surrounding vegetation.",
        "weather or maintenance may make base paths faint but still geometric.",
        "parking areas and access paths often adjoin the sports facility.",
        "the field is larger than a tennis or basketball court.",
        "its orientation varies because the diamond can point in any direction.",
        "overhead imagery reveals the distinctive diamond, arc, and foul-line layout.",
    ],
    "tennis court": [
        "it is a long narrow rectangle divided by a central net line.",
        "bright painted lines form service boxes and boundary rectangles.",
        "the playing surface may be green, blue, red, tan, or gray.",
        "its length is a little more than twice its width.",
        "the central net may appear as a thin line or narrow shadow.",
        "courts often occur in parallel groups with regular spacing.",
        "a fence commonly encloses the outer perimeter.",
        "it is frequently located near schools, parks, hotels, or residences.",
        "the surface texture is smooth and nearly uniform.",
        "doubles sidelines create nested bright rectangles along both sides.",
        "service lines divide each half into smaller geometric regions.",
        "players appear as tiny points and are not required for recognition.",
        "light poles may cast long thin shadows beside the court.",
        "adjacent courts may share fences and paved margins.",
        "the sharp right-angled outline contrasts with surrounding vegetation.",
        "weathering can fade the surface while line geometry remains visible.",
        "its footprint is smaller and narrower than most soccer fields.",
        "the court casts no broad shadow apart from fences and equipment.",
        "access paths often connect the enclosure to nearby buildings.",
        "overhead imagery emphasizes parallel courts and nested line markings.",
    ],
    "basketball court": [
        "it is a compact rectangular playing surface with painted boundaries.",
        "circular markings often appear at the center of the court.",
        "free-throw lanes form rectangular or key-shaped regions near each end.",
        "curved three-point lines arc around the baskets.",
        "the surface may be green, blue, red, tan, or gray.",
        "two basket structures lie near opposite short ends.",
        "basket poles may cast small narrow shadows onto the surface.",
        "it commonly occurs near schools, parks, and recreation facilities.",
        "the interior texture is smooth compared with grass or bare soil.",
        "bright line markings contrast with the main playing surface.",
        "the court is generally shorter and wider in proportion than a tennis court.",
        "fences may create a thin enclosing boundary around outdoor courts.",
        "multiple courts can appear side by side in a sports complex.",
        "the sharp corners and regular geometry distinguish it from open ground.",
        "players appear as tiny points and are not necessary for identification.",
        "the center circle helps distinguish it from a plain paved rectangle.",
        "weathered courts may show faint arcs and partially erased lines.",
        "nearby paths, buildings, or parking lots provide recreational context.",
        "its flat surface produces no broad object shadow.",
        "overhead imagery emphasizes the center circle, keys, and curved markings.",
    ],
    "ground track field": [
        "it contains an oval running track surrounding a central field.",
        "multiple narrow lanes form repeated concentric oval lines.",
        "the track surface is often red, brown, blue, or gray.",
        "the central area commonly appears green with grass or turf.",
        "two straight sections connect smoothly through curved ends.",
        "lane markings create a strong regular striped pattern.",
        "it usually occurs near schools, stadiums, or sports complexes.",
        "spectator stands may border one of the long straight sections.",
        "the footprint is much larger than individual courts.",
        "field-event zones may appear as small circles, pits, or runways nearby.",
        "soccer markings may be visible within the central field.",
        "light poles can cast thin radial shadows around the facility.",
        "the outer boundary is an elongated oval with smooth curves.",
        "access roads and parking areas often adjoin the stadium.",
        "the lane count is visible as closely spaced parallel curves.",
        "surface wear may create tonal variation along heavily used lanes.",
        "the central field contrasts in color and texture with the track.",
        "buildings or bleachers may cast shadows along the perimeter.",
        "its organized symmetry distinguishes it from natural oval landforms.",
        "overhead imagery reveals the iconic oval lanes and enclosed field.",
    ],
    "bridge": [
        "it forms a narrow structure spanning water, roads, or terrain gaps.",
        "the deck creates a continuous linear connection between two sides.",
        "it often aligns with roads or railways approaching each end.",
        "support piers may appear as repeated points beneath the deck.",
        "the bridge boundary is straighter and more engineered than the obstacle below.",
        "a long narrow shadow may run beside or beneath the deck.",
        "water remains visible on both sides of a river-crossing bridge.",
        "large bridges may have multiple parallel lanes or separate decks.",
        "suspension towers can cast tall distinctive shadows.",
        "approach ramps may curve before joining the main span.",
        "the deck surface often matches nearby road pavement in tone.",
        "rail bridges are generally narrower than multilane road bridges.",
        "crossings may be perpendicular or oblique to the feature below.",
        "vehicles can appear as small objects moving along the deck.",
        "guardrails may form thin bright lines along both edges.",
        "complex interchanges contain short bridges crossing other roads.",
        "its continuity distinguishes it from docks that end within water.",
        "construction materials may appear gray, pale concrete, or dark asphalt.",
        "shadows and occlusion indicate that the deck is elevated.",
        "overhead imagery emphasizes linear continuity across an interrupted surface.",
    ],
    "large vehicle": [
        "it appears as an elongated rectangular object on roads or paved areas.",
        "its footprint is clearly larger than nearby passenger cars.",
        "trucks may show separate cab and cargo-body sections.",
        "buses often have a long uniform roof with repeated rooftop details.",
        "the roof may appear white, gray, colored, or dark.",
        "it commonly occurs on highways, depots, ports, and industrial yards.",
        "parked examples may align in rows with wide regular spacing.",
        "moving examples follow lane direction and road geometry.",
        "a longer shadow may accompany its greater height and length.",
        "trailers can form very long narrow rectangles behind compact cabs.",
        "loading areas often contain several large vehicles beside warehouses.",
        "its boundary is clearest against uniform asphalt or concrete.",
        "large vehicles may cluster near terminals and logistics facilities.",
        "the long axis normally aligns with the direction of travel.",
        "roof equipment can create small contrasting patches.",
        "adjacent vehicles may merge in crowded transport yards.",
        "it is smaller than buildings but larger than ordinary cars.",
        "turning vehicles may appear oblique relative to nearby lane markings.",
        "its geometric footprint distinguishes it from irregular roadside objects.",
        "overhead imagery emphasizes roof length, sectioning, and transport context.",
    ],
    "small vehicle": [
        "it appears as a tiny compact rectangle or oval on a paved surface.",
        "its footprint is shorter and narrower than a bus or truck.",
        "the roof may be bright, dark, gray, red, or blue.",
        "dark windows can create small contrasting regions within the footprint.",
        "parked vehicles often form evenly spaced rows in parking lots.",
        "moving vehicles align with lanes on roads and intersections.",
        "a short narrow shadow may appear beside the object.",
        "it commonly occurs near buildings, roads, terminals, and commercial areas.",
        "the object may occupy only a few pixels at moderate resolution.",
        "bright vehicles contrast strongly with dark asphalt.",
        "dark vehicles contrast more clearly on concrete or pale ground.",
        "road markings are usually thinner and more continuous than vehicles.",
        "vehicle orientation varies in lots but follows traffic flow on roads.",
        "dense groups create repeated dot-like patterns in parking facilities.",
        "isolated examples may be confused with small rooftop objects.",
        "the sharp compact boundary separates it from pavement texture.",
        "cars and vans are commonly represented within this size category.",
        "partial tree shadows can obscure the vehicle roof.",
        "adjacent small vehicles may merge when spatial resolution is limited.",
        "overhead imagery emphasizes location, compact shape, and relative scale.",
    ],
    "helicopter": [
        "it has a compact fuselage with a long narrow tail boom.",
        "the main rotor may form a cross, line, or blurred circular span.",
        "a smaller tail rotor can appear near the end of the boom.",
        "its footprint is less wing-like than a fixed-wing aircraft.",
        "the cockpit end is broader than the tapered rear tail.",
        "it commonly occurs on helipads, airfields, ships, or open clearings.",
        "a circular helipad marking may surround or adjoin the object.",
        "rotor blades extend beyond the main body in overhead views.",
        "the aircraft may cast a compact body shadow with thin rotor shadows.",
        "its orientation can vary freely within a landing area.",
        "military types may appear dark green, gray, or camouflaged.",
        "civil types may be white or brightly colored.",
        "parked helicopters may align in organized rows at an airbase.",
        "the object is usually smaller than a commercial airplane.",
        "landing skids or wheels are rarely distinct at satellite resolution.",
        "the tail boom creates a characteristic asymmetric elongated silhouette.",
        "rotor diameter can be wider than the fuselage length.",
        "nearby support vehicles may provide aviation context.",
        "a sharp boundary is most visible on uniform paved aprons.",
        "overhead imagery emphasizes rotor geometry, body, and tail configuration.",
    ],
    "swimming pool": [
        "it is a contained water region with a sharp engineered boundary.",
        "the water often appears bright blue, cyan, turquoise, or dark blue.",
        "rectangular pools have straight sides and right-angled corners.",
        "recreational pools may have curved or irregular geometric outlines.",
        "a pale deck or paved border commonly surrounds the water.",
        "lane markings can appear as repeated dark lines in competition pools.",
        "it often occurs beside houses, hotels, schools, or sports centers.",
        "the interior texture is smoother than nearby vegetation.",
        "pool edges are sharper and more regular than natural ponds.",
        "small pools may appear as bright blue rectangles within residential parcels.",
        "large pools may include divided shallow and deep sections.",
        "sun glint can produce bright highlights on the water surface.",
        "buildings, fences, or trees may cast shadows across part of the pool.",
        "empty pools may appear pale but retain the same engineered outline.",
        "umbrellas or furniture can appear as tiny objects on the surrounding deck.",
        "the pool is isolated from natural drainage networks.",
        "water color contrasts with roofs, pavement, and lawns around it.",
        "diving platforms may create small protrusions or shadows at one end.",
        "multiple pools can occur together in a recreational complex.",
        "overhead imagery emphasizes contained blue water and geometric borders.",
    ],
    "roundabout": [
        "it is a circular road junction organized around a central island.",
        "approach roads connect radially to the circulating roadway.",
        "the central island may contain grass, pavement, trees, or decoration.",
        "lane markings curve continuously around the center.",
        "vehicles follow a ring-shaped traffic path around the island.",
        "the overall footprint is circular or slightly elliptical.",
        "three or more road branches commonly meet at the junction.",
        "splitter islands may appear as narrow shapes on the approaches.",
        "the ring road is darker or smoother than the central island.",
        "it occurs within urban, suburban, or highway road networks.",
        "small roundabouts may occupy a compact residential intersection.",
        "large examples can contain multiple circulating lanes.",
        "crosswalks may create bright striped markings near entry points.",
        "trees or monuments on the island may cast central shadows.",
        "the road branches distinguish it from an isolated circular tank.",
        "its engineered symmetry contrasts with irregular natural circles.",
        "traffic islands and curbs form nested circular boundaries.",
        "road orientation determines an irregular radial arrangement of exits.",
        "the center remains non-drivable while traffic surrounds it.",
        "overhead imagery reveals a ring with multiple connected road arms.",
    ],
    "soccer ball field": [
        "it is a large rectangular grass or turf playing area.",
        "bright boundary lines outline the long rectangular pitch.",
        "a center line divides the field into two equal halves.",
        "a center circle is visible near the middle of the pitch.",
        "rectangular penalty areas appear near both short ends.",
        "small goal boxes are nested inside the penalty areas.",
        "goals may cast short thin shadows beyond each end line.",
        "the surface commonly appears green with fine mowing texture.",
        "alternating mowing bands can run across the width of the field.",
        "it often occurs in schools, parks, stadiums, or sports complexes.",
        "spectator stands may border one or both long sides.",
        "light poles cast thin elongated shadows around the perimeter.",
        "multiple fields may appear in parallel organized groups.",
        "the field is larger than tennis and basketball courts.",
        "its markings are more rectangular than a baseball diamond layout.",
        "an oval running track may completely surround the pitch.",
        "worn goalmouths can appear as pale patches near each goal.",
        "the sharp outer boundary contrasts with surrounding roads or vegetation.",
        "players appear as tiny scattered points during active use.",
        "overhead imagery emphasizes the center circle and symmetric penalty boxes.",
    ],
    "plane": [
        "it has a slender fuselage crossed by two prominent wings.",
        "the overhead silhouette is approximately bilaterally symmetric.",
        "a tapered nose and rear tail define the main body axis.",
        "the wings are broader and longer than the tail stabilizers.",
        "it commonly occurs on airport runways, taxiways, and aprons.",
        "parked planes may line up beside terminal gates or hangars.",
        "the body often appears bright against dark paved surfaces.",
        "swept wings are common on jet-powered aircraft.",
        "straight wings are more common on small propeller aircraft.",
        "engines may appear as small pods under the wings.",
        "the tail fin can cast a compact shadow near the rear.",
        "wing and fuselage shadows may form a second offset silhouette.",
        "its footprint is larger and wider than nearby ground vehicles.",
        "the surface is smooth with little texture at satellite scale.",
        "orientation varies with runway direction or apron parking layout.",
        "the aircraft may occur alone or in organized airport clusters.",
        "airport markings and service vehicles provide strong contextual cues.",
        "the pointed nose distinguishes the front from the tail.",
        "partial occlusion by hangars can hide parts of the wings.",
        "overhead imagery emphasizes the cross-like aircraft geometry.",
    ],
    "harbor": [
        "it is a sheltered waterfront area containing docks and vessels.",
        "breakwaters or sea walls often define an enclosed water basin.",
        "multiple piers project from the shoreline into navigable water.",
        "ships and boats cluster along quays or within marina slips.",
        "the scene combines water, engineered shorelines, and port infrastructure.",
        "cargo harbors commonly adjoin warehouses, cranes, and paved yards.",
        "marinas create dense comb-like patterns of narrow docks.",
        "container stacks may form repeated colorful rectangles near the water.",
        "cranes cast long narrow shadows across docks or storage areas.",
        "navigation channels connect the protected basin to open water.",
        "water inside the harbor is often smoother than exposed coastal water.",
        "quay walls form sharp straight boundaries between land and water.",
        "roads and rail lines may converge on cargo-handling areas.",
        "anchored ships can appear in open parts of the basin.",
        "industrial tanks may occur near petroleum or bulk terminals.",
        "small service buildings line parts of the waterfront.",
        "sediment or wake patterns may change the water tone locally.",
        "the harbor footprint follows coastal geography and engineered barriers.",
        "its large spatial context distinguishes it from a single dock.",
        "overhead imagery reveals sheltered water integrated with dense maritime infrastructure.",
    ],
}


DLRSD_CLASSES = [
    "airplane", "bare soil", "buildings", "cars", "chaparral", "court",
    "dock", "field", "grass", "mobile home", "pavement", "sand", "sea",
    "ship", "tanks", "trees", "water",
]

ISAID_CLASSES = [
    "ship", "storage tank", "baseball diamond", "tennis court",
    "basketball court", "ground track field", "bridge", "large vehicle",
    "small vehicle", "helicopter", "swimming pool", "roundabout",
    "soccer ball field", "plane", "harbor",
]


def make_description(class_name: str, attribute: str) -> str:
    return f"an aerial image of {class_name}. {attribute}"


def main() -> None:
    expected = set(DLRSD_CLASSES) | set(ISAID_CLASSES)
    if set(ATTRIBUTES) != expected:
        missing = sorted(expected - set(ATTRIBUTES))
        extra = sorted(set(ATTRIBUTES) - expected)
        raise ValueError(f"class mismatch: missing={missing}, extra={extra}")

    descriptors = {}
    for class_name, attributes in ATTRIBUTES.items():
        if len(attributes) != 20:
            raise ValueError(f"{class_name!r} has {len(attributes)} attributes, expected 20")
        descriptions = [make_description(class_name, attribute) for attribute in attributes]
        if len(set(descriptions)) != 20:
            raise ValueError(f"{class_name!r} contains duplicate descriptions")
        descriptors[class_name] = descriptions

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(descriptors, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {len(descriptors)} classes and {sum(map(len, descriptors.values()))} descriptions to {OUTPUT}")


if __name__ == "__main__":
    main()
